# Generated by Django 6.0.2 on 2026-02-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
