# Generated by Django 6.0.2 on 2026-02-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_by',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
