# Generated by Django 6.0.2 on 2026-02-25 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_created_by'),
        ('articles', '0003_rename_ccreated_by_article_created_by'),
    ]

    operations = [
    ]
