name: itb-sains-kebumian

services:
  app:
    image: itb-sains-kebumian:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:${APP_PORT:-8080}:80"
    environment:
      - ENV=production
    restart: always
