# Generated by Django 6.0.2 on 2026-02-20 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('S2', 'S2 Magister'), ('S3', 'S3 Doktoral')], max_length=2)),
                ('study_option', models.CharField(max_length=200)),
                ('specialization', models.CharField(blank=True, max_length=200, null=True)),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('course_name', models.CharField(max_length=200)),
                ('sks', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=200)),
                ('cpps', models.CharField(blank=True, max_length=500, null=True)),
                ('cpmk', models.CharField(blank=True, max_length=500, null=True)),
                ('weekly_plan', models.CharField(blank=True, max_length=500, null=True)),
                ('ethics_note', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('year', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=200)),
                ('rubric', models.TextField()),
                ('weight', models.PositiveIntegerField()),
                ('cpl', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='courses.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.curriculum'),
        ),
        migrations.CreateModel(
            name='LearningMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=200)),
                ('implementation', models.CharField(max_length=200)),
                ('cpmk', models.CharField(max_length=200)),
                ('cpl', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='courses.course')),
            ],
        ),
    ]
