# Generated by Django 6.0.2 on 2026-02-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='specialization',
            field=models.CharField(blank=True, choices=[('IKLIM', 'Perubahan Iklim dan Transisi Energi'), ('BENCANA', 'Mitigasi Bencana Kebumian')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='study_option',
            field=models.CharField(choices=[('ATMOSFER', 'Sains Atmosfer'), ('OSEANOGRAFI', 'Oseanografi dan Interaksi Sistem Bumi'), ('KEBUMIAN', 'Sains Kebumian (khusus S3)')], max_length=20),
        ),
    ]
