# Generated by Django 6.0.2 on 2026-02-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_specialization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='study_option',
            field=models.CharField(choices=[('ATMOSFER', 'Sains Atmosfer'), ('OSEANOGRAFI', 'Oseanografi dan Interaksi Sistem Bumi'), ('KEBUMIAN', 'Sains Kebumian')], max_length=20),
        ),
    ]
