# Generated by Django 6.0.2 on 2026-02-24 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_program_alter_course_study_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='curriculum',
        ),
        migrations.DeleteModel(
            name='Curriculum',
        ),
    ]
