# Generated by Django 6.0.2 on 2026-02-24 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_curriculum_delete_curriculum'),
    ]

    operations = [
    ]
