# Generated by Django 6.0.2 on 2026-02-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='specialization',
            field=models.CharField(blank=True, choices=[('IKLIM', 'Perubahan Iklim dan Transisi Energi'), ('BENCANA', 'Mitigasi Bencana Kebumian')], max_length=100, null=True),
        ),
    ]
