# Generated by Django 6.0.2 on 2026-02-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='program',
            field=models.CharField(choices=[('S2', 'S2 Magister'), ('S3', 'S3 Doktoral')], max_length=20),
        ),
    ]
