# Generated by Django 6.0.2 on 2026-02-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='program',
            field=models.CharField(choices=[('S2 Magister', 'S2 Magister'), ('S3 Doktoral', 'S3 Doktoral')], max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
