# Generated by Django 6.0.2 on 2026-02-25 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_study_option'),
        ('courses', '0008_alter_course_program_alter_course_specialization'),
    ]

    operations = [
    ]
