# Generated by Django 6.0.2 on 2026-02-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_program_alter_course_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='program',
            field=models.CharField(choices=[('S2', 'S2 Magister'), ('S3', 'S3 Doktoral')], max_length=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='specialization',
            field=models.CharField(blank=True, choices=[('IKLIM', 'Perubahan Iklim dan Transisi Energi'), ('BENCANA', 'Mitigasi Bencana Kebumian')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='study_option',
            field=models.CharField(choices=[('ATMOSFER', 'Sains Atmosfer'), ('OSEANOGRAFI', 'Oseanografi dan Interaksi Sistem Bumi'), ('KEBUMIAN', 'Sains Kebumian')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
