# Generated by Django 6.0.2 on 2026-02-20 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='lecturers/')),
                ('name', models.CharField(max_length=255)),
                ('nip', models.CharField(max_length=100, unique=True)),
                ('position', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('webpage', models.URLField(blank=True, null=True)),
                ('sinta_id', models.CharField(blank=True, max_length=100, null=True)),
                ('researcher_id', models.CharField(blank=True, max_length=100, null=True)),
                ('scopus_author_id', models.CharField(blank=True, max_length=100, null=True)),
                ('orcid_id', models.CharField(blank=True, max_length=100, null=True)),
                ('research_interest', models.TextField(blank=True, max_length=500, null=True)),
                ('education_history', models.TextField(blank=True, max_length=500, null=True)),
                ('publications', models.TextField(blank=True, max_length=500, null=True)),
                ('projects', models.TextField(blank=True, max_length=500, null=True)),
                ('community_service', models.TextField(blank=True, max_length=500, null=True)),
                ('awards', models.TextField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='lecturers', to='lecturers.lecturercategory')),
            ],
        ),
        migrations.CreateModel(
            name='LecturerCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_lecturers', to='courses.course')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_courses', to='lecturers.lecturer')),
            ],
        ),
        migrations.AddField(
            model_name='lecturer',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='lecturers', through='lecturers.LecturerCourse', to='courses.course'),
        ),
    ]
