# Generated by Django 6.0.2 on 2026-02-18 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LecturerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('nip_nopeng', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('webpage', models.URLField(blank=True, null=True)),
                ('sinta_id', models.CharField(blank=True, max_length=100, null=True)),
                ('researcher_id', models.CharField(blank=True, max_length=100, null=True)),
                ('scopus_author_id', models.CharField(blank=True, max_length=100, null=True)),
                ('orcid_id', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('research_interest', models.TextField(blank=True, null=True)),
                ('education_history', models.TextField(blank=True, null=True)),
                ('publications', models.TextField(blank=True, null=True)),
                ('projects', models.TextField(blank=True, null=True)),
                ('community_service', models.TextField(blank=True, null=True)),
                ('awards', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturers', to='lecturers.lecturercategory')),
            ],
        ),
        migrations.CreateModel(
            name='LecturerCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_courses', to='lecturers.lecturer')),
            ],
        ),
    ]
