# Generated by Django 6.0.2 on 2026-02-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='awards',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='community_service',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='education_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='orcid_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='publications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='research_interest',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='research_projects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='researcher_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='scopus_author_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='sinta_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
