# Generated by Django 6.0.2 on 2026-02-25 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0002_lecturer_awards_lecturer_community_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturers_main', to='lecturers.lecturercategory'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='lecturers', to='lecturers.lecturercategory'),
        ),
    ]
